services:
  website:
    image: ruby:3.0.1-alpine
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    # command: bundle exec rails s -b 0.0.0.0
    env_file:
      - ".env"
    ports:
      - '3000:3000'
      - '9292:9292'
    container_name: api-ruby-resume-be
    environment:
      VIRTUAL_HOST: api.ai-resume.com, www.api.ai-resume.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: api.ai-resume.com, www.api.ai-resume.com
      LETSENCRYPT_EMAIL: danielfromarg@gmail.com
      DATABASE_URL: postgres://resume-app@postgres/resume-app
      PORT: 3000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: resume-app
      POSTGRES_DB: resume-app
  redis:
    image: "redis:7.0.8-alpine"
    command: redis-server
    volumes:
      - "redis:/data"

  cable:
    environment:
      DATABASE_URL: postgres://resume-app@postgres/resume-app
      PORT: 28080
    depends_on:
      - "redis"
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile.cable
    # command: puma -p 28081 -C config/puma_cable.rb
    ports:
      - "28080:28080"
    volumes:
      - ".:/app"
    env_file:
      - ".env"

  sidekiq:
    environment:
      DATABASE_URL: postgres://resume-app@postgres/resume-app
    depends_on:
      - "postgres"
      - "redis"
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - ".:/app"
    env_file:
      - ".env"

  nginx:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - website
    ports:
      - 80:80

volumes:
  redis:
  postgres:

networks:
  default:
    # Use a custom driver
    name: dan1d_network
    driver: bridge
