development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379" } %>
  channel_prefix: ia_resume_be_development

test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379" } %>
  channel_prefix: ia_resume_be_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379" } %>
  # channel_prefix: ia_resume_be_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>

  # adapter: async
